host: metabase-inside.intern.dev.nav.no
ingress:
  - https://data.intern.dev.nav.no/public
  - https://data.intern.dev.nav.no/app
  - https://data.intern.dev.nav.no/api/session/properties
  - https://data.intern.dev.nav.no/api/public
env: dev-gcp
