apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: metabase-proxy
  namespace: nada
  labels:
    team: nada
spec:
  image: {{image}}
  port: 8080
  replicas:
    min: 2
    max: 3
    cpuThresholdPercentage: 70
  env:
    - name: CERT_PATH
      value: "/etc/pki/tls/cacert.pem"
    - name: HOST
      value: {{host}}
  ingresses:
  {{#each ingress}}
    - {{.}}
  {{/each}}
  resources:
    limits:
      cpu: 400m
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 128Mi
  accessPolicy:
    outbound:
      external:
        - host: {{host}}

---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: metabase-proxy-alert
  namespace: nada
  labels:
    team: nada
spec:
  groups:
  - name: metabase-proxy-alert
    rules:
    - alert: InstanceDown
      expr: kube_deployment_status_replicas_available{namespace="nada", deployment="metabase-proxy"} == 0
      for: 2m
      annotations:
        consequence: Metabase proxy is unavailable
        action: "`kubectl describe pod <podname>` -> `kubectl logs <podname>`"
        summary: |-
          No metabase-proxy pods are running in {{env}}
      labels:
        namespace: nada
        severity: critical
